backend:
  name: "github"
  repo: premconvertors/santhiclone
  branch: main
  site_domain: https://santhiclone.pages.dev
  base_url: https://santhiclone.pages.dev
  auth_endpoint: /api/auth
media_folder: "src/images"
public_folder: "/images"
editor:
  preview: false
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blogs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Description", name: "description", widget: "string"}
      - { label: "Author", name: "author", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Tags", name: "tags", widget: "list", default: "post"}
      - { label: "Featured Image", name: "image", widget: "image"}
      - { label: "Image Caption", name: "imageAlt", widget: "string"}
      - { label: "YouTube Video URL", name: "youtube", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown"}